version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    command: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    cpu_count: 1
    mem_limit: 2gb
